### ISSUE TITLE
Repository needs a license.

### ISSUE THREAD

**Issue by benlk** [pale-shadow/1337-Noms-The-Hacker-Cookbook#1]
You intend to sell the compiled repository as a book - how will you arrange the licensing? Are contributions made to [the public domain under CC0](https://creativecommons.org/choose/zero/), under a [CC-BY](https://creativecommons.org/licenses/by/4.0/), a [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/), a [GFDL](https://en.wikipedia.org/wiki/GNU_Free_Documentation_License), or some other license?

The license should be added before any contributions are accepted, to avoid contaminating the repository with content that cannot be freely published or modified.

**Comment by devsecfranklin** [comment]
Completed. 

https://github.com/theDevilsVoice/1337-Noms-The-Hacker-Cookbook/blob/master/LICENSE
