### ISSUE TITLE
Suggestion: Merge 4Chan's /g/ "Gentoomen Library" restauraunt recipes 

### ISSUE THREAD

**Issue by ghost** [pale-shadow/1337-Noms-The-Hacker-Cookbook#29]
While browsing [this collection of books/ files](https://shodan.me/books/Extra/); I found a directory of "Restaurant Recipes". I thought it would be cool if we could merge these into this project. I think it would be fair to assume that the authors who provided their recipe's to the 4chan cookbook, wouldn't mind if we added these considering they aren't specifically licensed in any way. 

If we were to do this, I think we should organize these recipe's into a separate chapter, and attribute each individual author within their recipe as we're currently doing.

**Comment by Theyflower** [comment]
If it's legal to release those materials under the creative commons licence then you would be better off making a pull request with these changes.

**Comment by devsecfranklin** [comment]
I think the goal here is to collect things from people within the community. Not sure who submitted those recipes or what their expectations are as far as how they are used.
